language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-kolachi-website
  token:
    secure: U6+Gn1M4+vBW1f8gvierOTvz4pBuoJdN/NrDLpSX6u6nKYLVe3sMyIYFA6W9nqeJhdHNxaL+E82Vah4qFx3w5TOoziocBH7KwRaM9+54FmGKCO0gmB8QV8PGokdFJh8TVrPa8HsMMKYhp7+KMXbiy5Nedqp7lUn4SDahCD/h/8oFpLLgBwUPI8TNuWCBUXpl4CH/JkhOCNw8WzzyL1RHVhF7rRcZSwUnz8IOW3IA1Yx/SCkyWCe7K4vizP+wrlPk7du5DONOxIrMoJ6rbk/cDNXdRoSay6OByufxC4CmCM/yUQdaEJLmV/la1MWhD4gPaWwrFGFjxOa8FyiwdGxpoAfSEhnKLj0ZIpG4o55Ia1hnGU0b8fdTBqtGvWVzGvnd12BEEK+mdjb2xn30mI1Hgt3/WrxGCsOM6GXkp4ZPA39URR47vQaiWGq3GjYREwyaC4KqkNTn2tuQoJKAh3SNk+LAenWmuranmUHODOWL0eAsUcIB7FlB35dkDlYMlvCHWLszVhMQR7v+g0a2S2fj1eeAvV7hm04L+vhnr0oW7p8WwyGiQZ0cM08EROWqCY+H7m8KR9gYM4HjzU4y9gDGOlorMy95t69hdIxk9hUi0j3PaTKjHG5v4mO6mTiMfuAN96JTdnXHTBvDY+lYxT3PIDtZqhgulJPLot8rg7/L+7k=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: gdg-kolachi-website
  token:
    secure: U6+Gn1M4+vBW1f8gvierOTvz4pBuoJdN/NrDLpSX6u6nKYLVe3sMyIYFA6W9nqeJhdHNxaL+E82Vah4qFx3w5TOoziocBH7KwRaM9+54FmGKCO0gmB8QV8PGokdFJh8TVrPa8HsMMKYhp7+KMXbiy5Nedqp7lUn4SDahCD/h/8oFpLLgBwUPI8TNuWCBUXpl4CH/JkhOCNw8WzzyL1RHVhF7rRcZSwUnz8IOW3IA1Yx/SCkyWCe7K4vizP+wrlPk7du5DONOxIrMoJ6rbk/cDNXdRoSay6OByufxC4CmCM/yUQdaEJLmV/la1MWhD4gPaWwrFGFjxOa8FyiwdGxpoAfSEhnKLj0ZIpG4o55Ia1hnGU0b8fdTBqtGvWVzGvnd12BEEK+mdjb2xn30mI1Hgt3/WrxGCsOM6GXkp4ZPA39URR47vQaiWGq3GjYREwyaC4KqkNTn2tuQoJKAh3SNk+LAenWmuranmUHODOWL0eAsUcIB7FlB35dkDlYMlvCHWLszVhMQR7v+g0a2S2fj1eeAvV7hm04L+vhnr0oW7p8WwyGiQZ0cM08EROWqCY+H7m8KR9gYM4HjzU4y9gDGOlorMy95t69hdIxk9hUi0j3PaTKjHG5v4mO6mTiMfuAN96JTdnXHTBvDY+lYxT3PIDtZqhgulJPLot8rg7/L+7k=

